cursor #1a1b21
cursor_text_color #45464f

foreground            #1a1b21
background            #faf8ff
selection_foreground  #ffffff
selection_background  #c1c5dd
url_color             #4b5c92

color0   #121318
color1   #8a374d
color2   #266d31
color3   #afa92b
color4   #4b5d99
color5   #d7e0ff
color6   #4b5c92
color7   #272728
color8   #78797c
color9   #af576f
color10  #48a056
color11  #bdb838
color12  #586cb1
color13  #d7e0ff
color14  #8f9abd
color15  #d6d7db
